### ISSUE TITLE
Add a third mode to keep color values

### ISSUE THREAD

**Issue by JacobDB** [ahtohbi4/postcss-bgimage#4]
Would it be possible to add a third mode to keep the color value of a background rule? For example, I'd like this:

    .some-rule {
        background: url("../media/some-image.jpg") center center no-repeat #FF0000;
    }

To become this:

    .some-rule {
        background: #FF0000;
    }

Of course, this could get complicated what with all the different possible color formats (Hex, RGB, RGBA, name, etc.).

If this is too complex, I can just add a second line for the color fallback.

**Comment by ahtohbi4** [comment]
The purpose of the plugin is optimization of pages loading. But why do you need to separate a background color?

**Comment by JacobDB** [comment]
I use this script to help make my "critical" CSS better, then load in the full stylesheet asynchronously. Let's say I have a div that has a blue background with a logo overlaying it. When using this script, this would first load as a white div, then flash to blue with the logo when the main stylesheet finishes loading. It would be a nicer transition if it would first show the blue CSS background color with the "critical" CSS, then load in the image with the full stylesheet.

Does that make sense? If it's out of scope for this project, I totally get it. Thanks!

**Comment by ahtohbi4** [comment]
My apologies for so long waiting.

You can separate background-image value from shorthand one:
```css
.some-rule {
    background-image: url("../media/some-image.jpg");
    background: center center no-repeat #FF0000;
}
```

As a result, you will get:

```css
/* top.css */
.some-rule {
    background: center center no-repeat #FF0000;
}
```

```css
/* bottom.css */
.some-rule {
    background-image: url("../media/some-image.jpg");
}
```

Is it resolve your problem?
